owner: SimpleEdit
repo: status

sites:
  - name: Editor web app
    url: https://editor.simpleedit.repl.co
  - name: Website
    url: https://simpleedit.tk
  - name: Feedback portal
    url: https://simpleedit.canny.io
    
assignees:
  - thecoder876
  - wgyt

status-website:
  theme: dark
  logoUrl: https://raw.githubusercontent.com/SimpleEdit/simpleedit.github.io/main/assets/LOGO.png
  name: SimpleEdit Status
  navbar:
    - title: Website
      href: https://simpleedit.github.io
    - title: Docs
      href: https://simpleedit.gitbook.io/docs
    - title: GitHub
      href: https://github.com/$OWNER

# See https://upptime.js.org/docs/configuration for help.
